package com.example.backend.seeders;

import java.time.LocalDateTime;
import java.util.List;
import java.util.Random;
import java.util.stream.Collectors;
import java.util.stream.Stream;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.CommandLineRunner;
import org.springframework.stereotype.Component;

import com.example.backend.enums.Brand;
import com.example.backend.enums.FoodCategory;
import com.example.backend.enums.Size;
import com.example.backend.models.Food;
import com.example.backend.models.NutritionalInfo;
import com.example.backend.models.Supplier;
import com.example.backend.repositories.FoodRepository;
import com.example.backend.repositories.SupplierRepository;
import com.github.javafaker.Faker;

@Component
public class FoodSeeder implements CommandLineRunner {

    @Autowired
    private FoodRepository foodRepository;

    @Autowired
    private SupplierRepository supplierRepository;

    private final Faker faker = new Faker();
    private final Random random = new Random();
    private final String defaultImageUrl = "https://via.placeholder.com/600x400"; // Default image URL

    @Override
    public void run(String... args) throws Exception {
        // Clear existing data
        foodRepository.deleteAll();
        supplierRepository.deleteAll();

        // Create and save multiple suppliers
        List<Supplier> suppliers = createRandomSuppliers(10); // Create 10 suppliers
        supplierRepository.saveAll(suppliers);

        // Create and save sample foods
        for (int i = 0; i < 100; i++) {
            Food food = new Food();
            food.setName(faker.food().dish());
            food.setIngredients(generateRandomIngredients());
            food.setImageUrl(defaultImageUrl);
            food.setSize(getRandomSize());
            food.setBrand(getRandomBrand());
            food.setStockQuantity(faker.number().numberBetween(1, 100));
            food.setDiscount(faker.number().randomDouble(2, 0, 20));
            food.setCreatedAt(LocalDateTime.now());
            food.setUpdatedAt(LocalDateTime.now());
            food.setFoodCategory(getRandomCategory());
            food.setSupplier(getRandomSupplier(suppliers)); // Assign a random supplier
            food.setNutritionalInfo(createRandomNutritionalInfo());

            foodRepository.save(food);
        }
    }

    private List<String> generateRandomIngredients() {
        int numberOfIngredients = random.nextInt(3) + 1; // 1 to 3 ingredients
        return Stream.generate(() -> faker.food().ingredient())
                     .limit(numberOfIngredients)
                     .collect(Collectors.toList());
    }

    private Size getRandomSize() {
        Size[] sizes = Size.values();
        return sizes[random.nextInt(sizes.length)];
    }

    private Brand getRandomBrand() {
        Brand[] brands = Brand.values();
        return brands[random.nextInt(brands.length)];
    }

    private FoodCategory getRandomCategory() {
        FoodCategory[] categories = FoodCategory.values();
        return categories[random.nextInt(categories.length)];
    }

    private NutritionalInfo createRandomNutritionalInfo() {
        return new NutritionalInfo(
            faker.number().randomDouble(2, 100, 1000), // Calories
            faker.number().randomDouble(2, 0, 100), // Fat
            faker.number().randomDouble(2, 0, 100), // Protein
            faker.number().randomDouble(2, 0, 100) // Carbohydrates
        );
    }

    private List<Supplier> createRandomSuppliers(int number) {
        return Stream.generate(() -> createRandomSupplier())
                     .limit(number)
                     .collect(Collectors.toList());
    }

    private Supplier createRandomSupplier() {
        return new Supplier(
            null, // ID will be generated by MongoDB
            faker.company().name(), // Name
            faker.phoneNumber().phoneNumber(), // Phone number
            faker.address().fullAddress(), // Address
            LocalDateTime.now(), // Created at
            LocalDateTime.now()  // Updated at
        );
    }

    private Supplier getRandomSupplier(List<Supplier> suppliers) {
        return suppliers.get(random.nextInt(suppliers.size()));
    }
}
